### PR TITLE
Update import of URL utilities to be compatible with Django 2.0

### PR DESCRIPTION
**Pull request by joshourisman**
In Django 2.0, `django.core.urlresolvers` has been removed; both `reverse()` and `NoReverseMatch` should be imported from `django.urls`.

### CODE REVIEW

**Comment by bartTC** [comment]
Thanks @joshourisman!

Can you make your change backwards compatible please (see the failing tests)?

**Comment by bartTC** [comment]
I added Django 2.0 to both tox and travis in the `master` branch.

**Comment by joshourisman** [comment]
I think that change should do it, but now it looks like there's an issue with the travis.yml file.

**Comment by joshourisman** [comment]
Is there anything I can do to help you guys get this merged? As far as I can tell the only problem was with the travis YaML file; I think everything should actually be fine and it safe to merge at this point.

**Comment by bartTC** [comment]
Sorry @joshourisman. I just pushed a fix for the Travis file. Could you merge the `master` branch into yours? That will trigger a new check here and once its all green, I'll merge it.

**Comment by joshourisman** [comment]
Done and done!

**Comment by bartTC** [comment]
Thanks! I fix the remaning issues directly.

**Comment by bartTC** [comment]
FWIW, the urlreverse issue is not going to fix Django 2.0, there's a deeper issue with how relations are stored in Django. It's failing


```
    self,
  File "/tmp/tox/django-salmonella/py36-django-20/lib/python3.6/site-packages/django/contrib/admin/views/main.py", line 76, in __init__
    self.queryset = self.get_queryset(request)
  File "/tmp/tox/django-salmonella/py36-django-20/lib/python3.6/site-packages/django/contrib/admin/views/main.py", line 320, in get_queryset
    filters_use_distinct) = self.get_filters(request)
  File "/tmp/tox/django-salmonella/py36-django-20/lib/python3.6/site-packages/django/contrib/admin/views/main.py", line 130, in get_filters
    self.model, self.model_admin, field_path=field_path
  File "/Users/martin/Workspace/django-salmonella/salmonella/filters.py", line 34, in __init__
    self.form = self.get_form(request, field.rel, model_admin.admin_site)
AttributeError: 'ForeignKey' object has no attribute 'rel'
```

**Comment by joshourisman** [comment]
Well crap, you're right.

**Comment by joshourisman** [comment]
Apparently being sick has left me more out of it than I thought, didn't notice that this had already been fixed. Or that the project had been renamed…

**Comment by bartTC** [comment]
Has been fixed *and* it was renamed 😆

**Pull request merged**
