### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Gustavosdo**
Added support for Python 3.

### CODE REVIEW

**Comment by DZPM** [comment]
Django 1.9 support would be very useful to me. Guess I'll use @Gustavosdo 's fork. Thanks!

Do you know if django-salmonella is unsupported? No commits since 2013, and the PR's are not being merged.

**Comment by Gustavosdo** [comment]
Hello @DZPM, excuse me, I saw your message just now.
This is a great project, has a clean and well-written code. I also strange, last updated main branche was long ago ...

I'll try to keep my fork updated. By the way, I want to review the PR @DXist to merge it.

**Comment by bartTC** [comment]
Thank you for this! The whole project slipped, I'm going to clean it before I merge it.

**Comment by Gustavosdo** [comment]
Thank you @bartTC  :)

**Pull request merged**
